// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketingtool.Models;

#nullable disable

namespace Ticketingtool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ticketingtool.Models.JiraTaskDetail", b =>
                {
                    b.Property<string>("LOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("issueKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("issuetype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jiraProjectKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jiraProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reporter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("JiraTaskDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
